(function () {

const DAY = 86_400_000;
const ago = (days, hours = 0) => new Date(Date.now() - days * DAY - hours * 3_600_000).toISOString();

/** Demo library shown when no backend is configured. */
window.OA = window.OA || {};
window.OA.buildSeed = function () {
  return [
    {
      id: 'seed-1',
      title: 'Linear Algebra — Gilbert Strang',
      description: 'The full MIT 18.06 lecture series with problem sets and exams. Start here before touching machine learning.',
      type: 'Link',
      subject: 'Mathematics',
      topic: 'Linear Algebra',
      url: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
      tags: ['matrices', 'eigenvalues', 'mit'],
      createdAt: ago(21),
      bookmarked: true,
      completed: false,
      lastAccessed: ago(0, 3),
    },
    {
      id: 'seed-2',
      title: 'Operating Systems: Three Easy Pieces',
      description: 'A free, readable book that builds virtualization, concurrency and persistence one idea at a time.',
      type: 'Link',
      subject: 'Computer Science',
      topic: 'Operating Systems',
      url: 'https://pages.cs.wisc.edu/~remzi/OSTEP/',
      tags: ['os', 'concurrency', 'free'],
      createdAt: ago(18),
      bookmarked: false,
      completed: false,
      lastAccessed: ago(1, 2),
    },
    {
      id: 'seed-3',
      title: 'Neural Networks: Zero to Hero',
      description: 'Build backpropagation, a bigram model and a GPT from scratch, with code you can run alongside each lecture.',
      type: 'Link',
      subject: 'Machine Learning',
      topic: 'Deep Learning',
      url: 'https://karpathy.ai/zero-to-hero.html',
      tags: ['backprop', 'gpt', 'python'],
      createdAt: ago(14),
      bookmarked: true,
      completed: false,
      lastAccessed: ago(2),
    },
    {
      id: 'seed-4',
      title: 'The Algorithms — Python',
      description: 'Hundreds of algorithm implementations with tests. Good for reading a clean solution after you have tried your own.',
      type: 'Link',
      subject: 'Computer Science',
      topic: 'Algorithms',
      url: 'https://github.com/TheAlgorithms/Python',
      tags: ['dsa', 'python', 'practice'],
      createdAt: ago(12),
      bookmarked: false,
      completed: true,
      lastAccessed: ago(5),
    },
    {
      id: 'seed-5',
      title: 'Crafting Interpreters',
      description: 'Write a complete scripting language twice, first as a tree-walker and then as a bytecode VM.',
      type: 'Link',
      subject: 'Computer Science',
      topic: 'Compilers',
      url: 'https://craftinginterpreters.com/',
      tags: ['parsing', 'vm', 'language design'],
      createdAt: ago(10),
      bookmarked: false,
      completed: false,
    },
    {
      id: 'seed-6',
      title: "Paul's Online Math Notes",
      description: 'Clear notes with worked examples for calculus, differential equations and algebra.',
      type: 'Link',
      subject: 'Mathematics',
      topic: 'Calculus',
      url: 'https://tutorial.math.lamar.edu/',
      tags: ['calculus', 'notes', 'examples'],
      createdAt: ago(9),
      bookmarked: false,
      completed: true,
      lastAccessed: ago(4),
    },
    {
      id: 'seed-7',
      title: 'NCERT Physics — Class 12 textbooks',
      description: 'Official Part 1 and Part 2 textbooks. The baseline for board exams and the first pass for JEE theory.',
      type: 'PDF',
      subject: 'Physics',
      topic: 'Electromagnetism',
      url: 'https://ncert.nic.in/textbook.php',
      tags: ['ncert', 'board exams', 'jee'],
      createdAt: ago(8),
      bookmarked: true,
      completed: false,
    },
    {
      id: 'seed-8',
      title: 'GATE CSE previous year questions',
      description: 'Topic-wise question bank with community answers and explanations. Filter by year before you start a mock.',
      type: 'Link',
      subject: 'Exam Prep',
      topic: 'GATE CSE',
      url: 'https://gateoverflow.in/',
      tags: ['gate', 'pyq', 'mock'],
      createdAt: ago(6),
      bookmarked: false,
      completed: false,
      lastAccessed: ago(3),
    },
    {
      id: 'seed-9',
      title: 'Computer Networking: A Top-Down Approach',
      description: 'Companion site with slides, Wireshark labs and interactive exercises for each chapter.',
      type: 'Link',
      subject: 'Computer Science',
      topic: 'Networks',
      url: 'https://gaia.cs.umass.edu/kurose_ross/',
      tags: ['tcp', 'http', 'wireshark'],
      createdAt: ago(5),
      bookmarked: false,
      completed: false,
    },
    {
      id: 'seed-10',
      title: 'freeCodeCamp curriculum',
      description: 'The open-source curriculum behind the course platform. Read the challenges to see how topics are sequenced.',
      type: 'Link',
      subject: 'Computer Science',
      topic: 'Web Development',
      url: 'https://github.com/freeCodeCamp/freeCodeCamp',
      tags: ['html', 'javascript', 'curriculum'],
      createdAt: ago(3),
      bookmarked: false,
      completed: false,
    },
    {
      id: 'seed-11',
      title: 'JEE Main past papers',
      description: 'Official question papers and answer keys from the exam authority, organised by session.',
      type: 'Link',
      subject: 'Exam Prep',
      topic: 'JEE Main',
      url: 'https://jeemain.nta.nic.in/',
      tags: ['jee', 'pyq', 'answer keys'],
      createdAt: ago(2),
      bookmarked: true,
      completed: false,
    },
    {
      id: 'seed-12',
      title: 'Essence of Calculus',
      description: 'Ten short videos that build geometric intuition for derivatives, integrals and the chain rule.',
      type: 'Link',
      subject: 'Mathematics',
      topic: 'Calculus',
      url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr',
      tags: ['intuition', 'derivatives', 'visual'],
      createdAt: ago(1),
      bookmarked: false,
      completed: false,
    },
  ];
};
})();
